### ISSUE TITLE
_

### ISSUE THREAD

**Issue by kelvennn** [VT-NLP/Event_Query_Extract#2]
_

**Comment by Foxaver** [comment]
> _

Hey friend, I want to ask you how to get the. txt files（train.txt,dev.txt,test.txt）

**Comment by kelvennn** [comment]
Friend,
I got the txt files from another paper's code in github, which are just contain files' name from origin data so that splited them into train, dev and test data.
I'll send them to you if you want.


覃冠球
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VT-NLP/Event_Query_Extract"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 中午11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VT-NLP/Event_Query_Extract] _ (Issue #2)





  
_
  
Hey friend, I want to ask you how to get the. txt files（train.txt,dev.txt,test.txt）

**Comment by sijiawang0221** [comment]
The .txt files can be generated by this line https://github.com/VT-NLP/Event_Query_Extract/blob/main/setup.sh#L16

**Comment by Foxaver** [comment]
> Friend, I got the txt files from another paper's code in github, which are just contain files' name from origin data so that splited them into train, dev and test data. I'll send them to you if you want. 覃冠球 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VT-NLP/Event_Query_Extract" ***@***.***&gt;; 发送时间:&nbsp;2022年8月8日(星期一) 中午11:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [VT-NLP/Event_Query_Extract] _ (Issue #2) _ Hey friend, I want to ask you how to get the. txt files（train.txt,dev.txt,test.txt） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Oh, thank you so much, friend. My email is 1597262022@qq.com.I really appreciate it

**Comment by Foxaver** [comment]
> The .txt files can be generated by this line https://github.com/VT-NLP/Event_Query_Extract/blob/main/setup.sh#L16

Thank U！！！I see that

**Comment by kkkeepgoing** [comment]
> Friend, I got the txt files from another paper's code in github, which are just contain files' name from origin data so that splited them into train, dev and test data. I'll send them to you if you want. 覃冠球 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "VT-NLP/Event_Query_Extract" ***@***.***&gt;; 发送时间:&nbsp;2022年8月8日(星期一) 中午11:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [VT-NLP/Event_Query_Extract] _ (Issue #2) _ Hey friend, I want to ask you how to get the. txt files（train.txt,dev.txt,test.txt） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Can you share the split .txt file with me? I really appreciate it. My email address is zhonghanmeng2021@163.com.
