### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by simon-p-j-r** [VT-NLP/Event_Query_Extract#7]
对作者所写文章非常感兴趣，读了几遍，想复现论文。但是数据集以及数据处理始终困扰，请问raw_data在经过ACE_ERE_Scripts处理过后的.csv文件放进./data/ace_en/processed_data and ./data/ere_en/processed_data respectively之后；运行bssh setup.sh之前。还要经过什么处理呢

**Comment by Tsukiaa** [comment]
请问有原始数据集可以分享一下吗？
